# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics'),
        ),
    ]
