# Generated by Django 2.1 on 2020-04-20 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='images')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Indie', 'Indie'), ('Fantasy', 'Fantasy'), ('RPG', 'RPG'), ('Simulator', 'Simulator'), ('Shooter', 'Shooter'), ('Sports and racing', 'Sports and racing'), ('Strategy', 'Strategy')], max_length=17)),
                ('genre_two', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Indie', 'Indie'), ('Fantasy', 'Fantasy'), ('RPG', 'RPG'), ('Simulator', 'Simulator'), ('Shooter', 'Shooter'), ('Sports and racing', 'Sports and racing'), ('Strategy', 'Strategy')], max_length=17)),
                ('genre_three', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Indie', 'Indie'), ('Fantasy', 'Fantasy'), ('RPG', 'RPG'), ('Simulator', 'Simulator'), ('Shooter', 'Shooter'), ('Sports and racing', 'Sports and racing'), ('Strategy', 'Strategy')], max_length=17)),
                ('works_on', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], max_length=7)),
                ('release_date', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('pegi_rating', models.CharField(blank=True, choices=[('3', '3'), ('7', '7'), ('12', '12'), ('16', '16'), ('18', '18')], max_length=2)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='images')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
