# Generated by Django 2.1.5 on 2020-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='multiplayer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='single_player',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='works_on_three',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='works_on_two',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], max_length=7),
        ),
    ]
