# Generated by Django 2.1.5 on 2020-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
