# Generated by Django 2.1.5 on 2020-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200422_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='Null', max_digits=5),
        ),
    ]
