# Generated by Django 2.1.5 on 2020-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200428_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
