# Generated by Django 2.1.5 on 2020-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200428_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
